### ISSUE TITLE
The Wanderer Alpha Surveillance missions should be modified to deal with the Aben systems

### ISSUE THREAD

**Issue by nathan-b** [Adde-Endless-Sky/Aben#5]
There's a missions where you're tracking the Alphas via their jump drive signature. When you jump into a system, your passenger (Elias) will tell you the direction to check next. However, none of the Aben systems have this text so if the player has to just guess where to jump next.

**Comment by AddeCurator** [comment]
Resolved. Created an invisible mission to trigger alongside Alpha Surveillance that provides on enter dialogs for northern Aben systems.
